global:
  scrape_interval: 10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - 127.0.0.1:9090
  - job_name: app
    static_configs:
      - targets:
        - app:2112
  - job_name: cadvisor
    static_configs:
      - targets:
        - cadvisor:8080
